controller_list:
  - name: fake_hector_group_controller
    type: $(arg fake_execution_type)
    joints:
      - virtual_joint
initial:  # Define initial robot poses per group
#  - group: hector_group
#    pose: home

  []